### ISSUE TITLE
reorganize code in the laclasse "standard way"

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-admin-panel#47]

**Comment by cycojesus** [comment]
- [ ] rename helper/ into lib/helpers/
- [ ] move public/* into public/app/*
- [ ] move public/app/js/app/* into public/app/js/
- [ ] inline content of public/app/js/constants.js in views/layout.erb

---

- [ ] reinstall the vendor libs in /public/app/js/lib/ using bower

**Comment by cycojesus** [comment]
- [ ] reinstall the vendor libs in /public/app/js/lib/ using bower

**Comment by cycojesus** [comment]
- [ ] update *.sample so that they have correct values

**Comment by HuguesGithub** [comment]
- [x] rename helper/ into lib/helpers/ : Done, bundle ok. Push on develop-47.

**Comment by HuguesGithub** [comment]
- [x] move public/* into public/app/*
- [x] move public/app/js/app/* into public/app/js/
All done, bundle ok.
checking path to js files

**Comment by HuguesGithub** [comment]
All in one :
- [x] rename helper/ into lib/helpers/
- [x] move public/* into public/app/*
- [x] move public/app/js/app/* into public/app/js/
- [ ] inline content of public/app/js/constants.js in views/layout.erb
- [ ] reinstall the vendor libs in /public/app/js/lib/ using bower
- [ ] update *.sample so that they have correct values

**Comment by HuguesGithub** [comment]
- [x]     rename helper/ into lib/helpers/
- [x]     move public/* into public/app/*
- [x]     move public/app/js/app/* into public/app/js/
- [x]     inline content of public/app/js/constants.js in views/layout.erb
- [x]     update *.sample so that they have correct values
- [ ]     reinstall the vendor libs in /public/app/js/lib/ using bower

**Comment by HuguesGithub** [comment]
- [ ] explode controllers, services, filters, directives into individual files

- [ ] rubocop
    - [ ] add to Gemfile
    - [ ] bundle install
    - [ ] add .rubocop.yml
    - [ ] generate .rubocop_todo.yml ( rubocop--auto-gen-config )
    - [ ] pass rubocop --auto-correct
    - [ ] fix remaining errors
    - [ ] add rubocop testing to travis

**Comment by HuguesGithub** [comment]
- [ ] reinstall the vendor libs in /public/app/js/lib/ using bower
- [x] explode controllers, services, filters, directives into individual files
----> Partially done. Doesn't seem useful for directives.

- [ ] rubocop
    - [ ] add to Gemfile
    - [ ] bundle install
    - [x] add .rubocop.yml
    - [x] generate .rubocop_todo.yml ( rubocop--auto-gen-config )
    - [ ] pass rubocop --auto-correct
    - [ ] fix remaining errors
    - [ ] add rubocop testing to travis

auto-correct not executed (in order to understand the meaning of the errors)
fixing remaining errors close to be done (7 offenses remaining)

**Comment by HuguesGithub** [comment]
- [ ] reinstall the vendor libs in /public/app/js/lib/ using bower

- [ ] rubocop
    - [ ] add to Gemfile
    - [ ] bundle install
    - [x] pass rubocop --auto-correct
    - [x] fix remaining errors
    - [x] add rubocop testing to travis

auto-correct not executed (in order to understand the meaning of the errors)
fixing remaining errors close to be done (7 offenses remaining)

**Comment by HuguesGithub** [comment]
- [ ] reinstall the vendor libs in /public/app/js/lib/ using bower

- [x] rubocop
    - [x] add to Gemfile
    - [x] bundle install

**Comment by HuguesGithub** [comment]
- [x] reinstall the vendor libs in /public/app/js/lib/ using bower
